### ISSUE TITLE
Error when adding card

### ISSUE THREAD

**Issue by aidbish** [Shaegi/Homeassistant-WLED-Card#1]
Hi
just trying the card for WLED

when i add teh config, its says its missing the entity, if i add the entity for the wled strip, then  get a blank display

in regrads to adding the resource to my lovelaceui-yaml, there are some resources in the example that are missing, do i need to download those?

**Comment by aidbish** [comment]
All fixed, just needed to add the entity and download the other stuff listed in the resources

working well so far, well done

**Comment by BartoilPerso** [comment]
I'm thinking I'm having the same issue. I've set the Entity, Type, Topic, Title, and IP. I downloaded and loaded all the dependencies, yet I'm still seeing a blank card. This would work with the new UI editor, correct? I've gotten other cards to work so far, so maybe I'm still missing something

Thanks
