### ISSUE TITLE
WLED with HA integration?

### ISSUE THREAD

**Issue by stefancvetkovic** [Shaegi/Homeassistant-WLED-Card#10]
Hello I added all the files into my www folder but I m getting this:
![image](https://user-images.githubusercontent.com/13699747/89044061-bf132e00-d349-11ea-928d-324a125faf8d.png)

here is the my resource file:
![image](https://user-images.githubusercontent.com/13699747/89044179-e964eb80-d349-11ea-9766-342fdee3639e.png)

**Comment by MarvinWalther** [comment]
I think, there has to be a `/local` in front of every entry. For example: `/local/lib/iro.min.js`.

**Comment by stefancvetkovic** [comment]
I added /local/ prefix, its the same.
this is my folder structure with files.
https://i.imgur.com/JeTBcbM.png
https://i.imgur.com/CZplQNy.png

Also, is this card can work with HA INtegration WLED? without putting any mqtt topic?

**Comment by stefancvetkovic** [comment]
https://i.imgur.com/bjT0axV.png

**Comment by daranto** [comment]
Hey,

you need to edit the lovelace_resources in the .storage folder. 

Change the "type": "module", to "type": "js"

After the change it should work. 

  - url: /local/lib/tingle.min.css
    type: css
  - url: /local/wled_control/static/wled.css
    type: css
  - url: /local/wled_control/static/effects.js
    type: js _<-- change to js in lovelace_ressources_
  - url: /local/wled_control/static/fastLEDPallete.js
    type: js _<-- change to js in lovelace_ressources_
  - url: /local/lib/tingle.min.js
    type: js _<-- change to js in lovelace_ressources_
  - url: /local/lib/iro.min.js
    type: js _<-- change to js in lovelace_ressources_
  - url: /local/wled_control/wled_control.js
    type: module

**Comment by Shaegi** [comment]
Since this issue seem to be resolved, I will close it.
