### ISSUE TITLE
can someone tell me what i need to add to the lib folder??

### ISSUE THREAD

**Issue by damver** [Shaegi/Homeassistant-WLED-Card#11]
hey guys,

i am a rookie to hassio

and i made a wled controller yesterday.

now i want it to add this controlpanel to my hassio.
but i cant figure out what to add to the lib folder.
can someone help me out?
maybe with sharing a screenshot?

or something?

kind regards
damian

**Comment by Shaegi** [comment]
Hi,
you need to add both dependencies (tingle.js and iro.js) to your lib. Therefore download them from their respective homepage. 
You should have about this folder structure:
``` 
lib/tingle.min.css
ib/tingle.min.js
lib/iro.min.js 
```

Checkout the readme for further informations: https://github.com/Shaegi/Homeassistant-WLED-Card/blob/master/README.md
