### ISSUE TITLE
nothing i can't get it to work

### ISSUE THREAD

**Issue by mihaiandrei1489** [Shaegi/Homeassistant-WLED-Card#13]
nothing i can't get it to work

**Comment by mihaiandrei1489** [comment]
[
![immagine](https://user-images.githubusercontent.com/17111642/103136914-c35b3180-46c4-11eb-81f8-89b0a57d9494.png)
](url)

**Comment by Shaegi** [comment]
Can you share please more about how you set it up? Seems like youre config does not recognize the custom card. Be sure you followed all steps in the setup-guide.
