### ISSUE TITLE
Blank Card

### ISSUE THREAD

**Issue by BartoilPerso** [Shaegi/Homeassistant-WLED-Card#3]
I feel this issue is related, at least I have the same results so far. I've added the light to my config.yaml, I can control it from the unused entities section (when I don't have it tied to the card) but the card doesn't even show up unless I'm in the UI Editor. 

From my config.yaml:
 light:
      - platform: mqtt
        name: "striplights1"
        brightness_state_topic: "wled/1/g"
        rgb_state_topic: "wled/1/c"
        command_topic: "wled/1"
        brightness_command_topic: "wled/1"
        rgb_command_topic: "wled/1/col"
        rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue)}}"
        effect_command_topic : "wled/1/api"
        effect_list: 
        - "[FX=00] Solid"
        - "[FX=01] Blink"
        - "[FX=02] Breathe"
        - "[FX=03] Wipe"
....

And the custom card code:
    cards:
      - entity: light.striplights1
        ip: 192.168.xxx.xxx
        title: WLED Strip 1
        topic: wled/1
        type: 'custom:wled-control-card'

I'm hoping it's a simple issue somewhere that I've just missed now that I'm thinking it's more complicated, but who knows... Any support would be great! Thanks!

**Comment by BartoilPerso** [comment]
Well, after trying to install another custom card I realized one silly mistake, so let's pretend I'm not an amateur. However now I get a toggle, but nothing else..

**Comment by BartoilPerso** [comment]
It appears as though the issue is based in SSL. From the Chrome console:

```
wled_control.js:19
Mixed Content: The page at 'https://[myaddress].duckdns.org:8123/lovelace/5' was loaded over HTTPS, but requested an insecure resource 'http://192.168.xxx.xxx/win'. This request has been blocked; the content must be served over HTTPS.

```

Any suggestions?

**Comment by definitelynotkk** [comment]
> Well, after trying to install another custom card I realized one silly mistake, so let's pretend I'm not an amateur. However now I get a toggle, but nothing else..
Hi
Can you please specify what is the mistake. i also got a blank card.

**Comment by Shaegi** [comment]
Sorry about late answering, wasn't receiving any notifications about your issue...

The last one is related to this https://github.com/Aircoookie/WLED/issues/99 older versions of WLED didn't send right CORS headers. Flashing a newer version of WLED should solve this issue. If you still have trouble with it, just let me know.
