### ISSUE TITLE
Error in Home Assistant

### ISSUE THREAD

**Issue by jhopkins213** [Shaegi/Homeassistant-WLED-Card#4]
I'm most likely doing something stupid but i get this error
You need to define an entity
{
  "type": "custom:wled-control-card",
  "topic": "wled/stripone",
  "ip": "192.168.86.32",
  "title": "WLED Strip"
}

This is my yaml code
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:wled-control-card
            topic: "wled/stripone"
            ip: "192.168.86.32"
            title: WLED Strip

**Comment by mpitz** [comment]
Same here

**Comment by Shaegi** [comment]
Sorry about my inactivity. Somehow I didn't watch the repo and wasn't receiving any notifications. 

I just updated the repo for newer features which I didn't publish to the repo yet including brightness sliders and so on. 

Now to your problem: I gave it a look and it seems like I forgot to remove some experimental code from the card which then threw the error when you won't set an entity property in the lovelace-ui.yaml. Sorry! I updated the repo so you won't need to declare an entity anymore... If you don't want to clone again you can just add `entity: "someEntity"` to your card which should resolve the error. 

If you still have trouble with setting it up let me know!

**Comment by jhopkins213** [comment]
Fallowed your instructions but I thinks it's because I'm using https for home assistant I no longer get the error but I get this isnted when I inspect the page in chrome 
wled_control.js:20 Mixed Content: The page at 'https://username.duckdns.org:8123/lovelace/hidden_view' was loaded over HTTPS, but requested an insecure resource 'http://192.168.86.223/win'. This request has been blocked; the content must be served over HTTPS.
