### ISSUE TITLE
Custom element doesn't exist: wled-control-card

### ISSUE THREAD

**Issue by watertime** [Shaegi/Homeassistant-WLED-Card#8]
OK still learning Home assistant
Version: HassOS 3.12

Added to raw configuration editor:
resources:
  - type: css
    url: /lib/tingle.min.css
  - type: css
    url: /wled_control/static/wled.css
  - type: js
    url: /wled_control/static/effects.js
  - type: js
    url: /wled_control/static/fastLEDPallete.js
  - type: js
    url: /lib/tingle.min.js
  - type: js
    url: /lib/iro.min.js
  - type: module
    url: /wled_control/wled_control.js

Added to config folder:
  lib folder containing:
![lib folder](https://user-images.githubusercontent.com/61945710/76173883-dfafd100-6179-11ea-83de-5898bda45edd.PNG)

Added to wled_contol
![image](https://user-images.githubusercontent.com/61945710/76173896-0241ea00-617a-11ea-8c21-5530af8f3f55.png)

My tree is like this:
![image](https://user-images.githubusercontent.com/61945710/76173910-26053000-617a-11ea-9287-f5c557512435.png)

I added the card and and getting Custom element doesn't exist: wled-control-card
![image](https://user-images.githubusercontent.com/61945710/76173932-47661c00-617a-11ea-94d3-7c155a181866.png)

When I go in chrome and look at the errors I get 404 files not found
![image](https://user-images.githubusercontent.com/61945710/76173967-79777e00-617a-11ea-9d22-12203ae9f6cb.png)

In firefox I get get this error saying it was block
![image](https://user-images.githubusercontent.com/61945710/76174025-eee34e80-617a-11ea-89fc-e9d61d93a78c.png)

Nothing is SSL and I don't see anything related in the other issues (or I missed it)

I have restore to a version before I tried this and redid everything still with no luck.

All the paths appear to be correct. Really stumped on this one.

Looking for where to start.

Thanks

**Comment by Shaegi** [comment]
As far as I know custom cards have to be placed in a `/www` - directory in hassio root folder. So create a new folder in your root and copy `lib` and `wled_control` into it.  Hope this will help :)

**Comment by watertime** [comment]
OK, this kicked my ass but I hope I can help someone else out. In the new version of Home Assistant you no longer use the lovelace.config.yaml

Everything is edited in the  raw configuration editor(Overview>3 dots>Configure UI>3 dots again). You will need to put the statements that would have been in lovelace.config.yaml here as shown before the home:
![image](https://user-images.githubusercontent.com/61945710/76263578-a046ba80-6235-11ea-9419-7c7edf147694.png)

Then create the www file and put the 2 files lib and wled_control as described in the instructions.

To create the card. Select a manual card and make it look like this
![image](https://user-images.githubusercontent.com/61945710/76263773-2cf17880-6236-11ea-85f2-48b69f71b366.png)

and enjoy!

thanks for the awesome work on this card!

**Comment by tapd** [comment]
I've been through this several times and have the exact config as the instructions, which is pretty much what's described above. I'm still getting 'Custom element doesn't exist: wled-control-card'. Is there anything else I could have missed?
